[build]
  command = "python build.py"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/servicios"
  to = "/servicios.html"
  status = 200

[[redirects]]
  from = "/sobre-mi"
  to = "/sobre-mi.html"
  status = 200

[[redirects]]
  from = "/contacto"
  to = "/contacto.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
